/**
 * Blob-based Report & Executable Script Export Manager
 * Formats: Executable Bash (.sh), Text (.txt), Markdown (.md), JSON (.json)
 */

export function exportCommandsToFile(commandsList, format = "txt", targetIp = "192.168.1.1") {
  if (!commandsList || commandsList.length === 0) {
    alert("No commands available to export.");
    return;
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  let content = "";
  let mimeType = "text/plain;charset=utf-8";
  let filename = `nmap_scan_recipes_${timestamp}.${format}`;

  switch (format) {
    case "sh":
      filename = `nmap_audit_script_${timestamp}.sh`;
      mimeType = "application/x-sh;charset=utf-8";
      content = generateBashScriptContent(commandsList, targetIp);
      break;

    case "markdown":
    case "md":
      filename = `nmap_scan_report_${timestamp}.md`;
      mimeType = "text/markdown;charset=utf-8";
      content = `# Nmap Security Audit Report & Recipes
Generated on: ${new Date().toLocaleString()}
Target IP / Network: ${targetIp}
Total Scans: ${commandsList.length}

---

${commandsList.map((cmd, idx) => `
### ${idx + 1}. ${cmd.name}
- **Category:** ${cmd.category}
- **Speed:** ${cmd.speedLevel}/5 | **Stealth:** ${cmd.stealthLevel}/5 | **Risk:** ${cmd.riskLevel}
- **Syntax:**
\`\`\`bash
${cmd.commandPattern.replace("{target}", targetIp).replace("{ports}", "").replace("{timing}", "-T4").replace("{flags}", "")}
\`\`\`
- **Description:** ${cmd.description}
- **Use Case:** ${cmd.whenToUse}
`).join('\n---\n')}
`;
      break;

    case "json":
      filename = `nmap_export_${timestamp}.json`;
      mimeType = "application/json;charset=utf-8";
      content = JSON.stringify({
        generatedAt: new Date().toISOString(),
        targetIp: targetIp,
        totalCommands: commandsList.length,
        commands: commandsList
      }, null, 2);
      break;

    case "txt":
    default:
      filename = `nmap_commands_${timestamp}.txt`;
      content = `========================================================
NMAP SCAN RECIPES & COMMAND REPORT
Generated: ${new Date().toLocaleString()}
Target IP: ${targetIp}
========================================================

` + commandsList.map((cmd, idx) => `
[${idx + 1}] ${cmd.name.toUpperCase()}
Category: ${cmd.category}
Command:  ${cmd.commandPattern.replace("{target}", targetIp).replace("{ports}", "").replace("{timing}", "-T4").replace("{flags}", "")}
Desc:     ${cmd.description}
--------------------------------------------------------
`).join('\n');
      break;
  }

  // Trigger file download using Blob API
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generateBashScriptContent(commandsList, targetIp) {
  return `#!/usr/bin/env bash
# ==============================================================================
# AUTOMATED NMAP SECURITY AUDIT SCRIPT
# Generated by Nmap Intelligence & Scan Builder Platform
# Target IP / Subnet: ${targetIp}
# Date: ${new Date().toLocaleString()}
# WARNING: Run ONLY against authorized infrastructure!
# ==============================================================================

set -e

TARGET="${targetIp}"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
OUTPUT_DIR="./nmap_audit_results_\${TIMESTAMP}"

echo "[+] Creating output directory: \${OUTPUT_DIR}"
mkdir -p "\${OUTPUT_DIR}"

echo "[+] Starting Nmap Security Audit for Target: \${TARGET}"
echo "=========================================================="

${commandsList.map((cmd, idx) => {
  const rawCmd = cmd.commandPattern
    .replace("{target}", "$TARGET")
    .replace("{ports}", "")
    .replace("{timing}", "-T4")
    .replace("{flags}", "");
  
  const safeName = cmd.id || `scan_${idx + 1}`;
  return `
# Step ${idx + 1}: ${cmd.name}
echo "[*] [${idx + 1}/${commandsList.length}] Running: ${cmd.name}..."
${rawCmd} -oN "\${OUTPUT_DIR}/${safeName}.nmap" || echo "[-] Step ${idx + 1} finished with non-zero exit code."
echo "[+] Results saved to \${OUTPUT_DIR}/${safeName}.nmap"
echo "----------------------------------------------------------"
`;
}).join('')}

echo "[+] Security Audit Complete! All log files saved in \${OUTPUT_DIR}/"
`;
}
